project:
  type: website
  resources:
    - CNAME

website:
  title: "dslc.io"
  repo-url: https://github.com/dslc-io/dslc-io
  # repo-actions: [issue]
  # google-analytics: "G-QQ1ZV766J5"
  # cookie-consent: true
  favicon: images/dslc_stacked_black_150x150.png
  twitter-card: true
  open-graph: true
  navbar:
    background: "#222"
    logo: images/dslc_edu_line_gray.png
    logo-alt: "Data Science Learning Community"
    title: false
    tools:
      - icon: mastodon
        href: https://fosstodon.org/@DSLC
      - icon: linkedin
        href: https://www.linkedin.com/company/dslc-io
      - icon: youtube
        href: https://dslc.io/youtube
      - icon: github
        href: https://github.com/dslc-io/dslc-io
    left:
      - href: bookclubs.qmd
      - href: question_answering.qmd
      # - href: donate.qmd
      - text: About Us
        menu:
        - href: about.qmd
        - href: faq.qmd
        - href: fiscal_sponsorship.qmd
        - href: code_of_conduct.qmd
        - href: privacy.qmd
        - href: license.qmd
        - href: governance.qmd
  page-footer:
    background: "#222"
    center:
      This website is licensed under a [Creative Commons Attributions 4.0
      International License](https://creativecommons.org/licenses/by/4.0/).
      Copyright 2024 the Data Science Learning Community.
format:
  html:
    theme: [flatly, custom.scss]
    toc: false
    link-external-newwindow: true
