---
title: "Privacy"
---

This notice describes how the Data Science Learning Community (DSLC for short) collects and uses data about you.

## What is the Data Science Learning Community?

DSLC is a community managed by volunteers. The community is primarily adminstered by Jon Harmon. The community is not yet a legal entity.

The DSLC Slack is hosted by Slack Technologies. See [their privacy policy here](https://slack.com/legal).

## How does DSLC collect data about me?

DSLC collects data about you:

* when you browse [rfordatasci.com](https://www.rfordatasci.com/).
* when you create and use an account on our [Slack team](http://r4ds.io/join).
* when you post, send private messages, answer a thread, or otherwise participate in the DSLC Slack.
* when you browse our [YouTube channel](https://www.youtube.com/R4DSOnlineLearningCommunity).
* when you participate in an Data Science Learning Community project, such as our mentorship pairing program.

## What does DSLC collect about me, and why?

**When you browse [rfordatasci.com](https://www.rfordatasci.com/),** we collect Google Analytics data. We use this data to better understand where our users are coming from.

**When you create and use an account on our [Slack team](http://r4ds.io/join),** we collect an email address and other optional information. 

* Slack requires this information for account creation. 
* If we need to talk to you about our [Code of Conduct](../conduct), we may contact you via this email address. 
* We do not intentionally share this email address with anyone, but Slack may make it available.
* You can erase your personal information from your account at any time.
* Slack stores your account data as long as your account remains open.

**When you post, send private messages, answer a thread, or otherwise participate in the DSLC Slack**, you generate content that may be accessible via Slack applications and the Slack API. DSLC uses this data to improve the experience, and may share posts outside of the DSLC Slack (for example, in a blog post or presentation about the mentoring process). All answers shared on the DSLC Slack are considered to be licensed under the [Creative Commons CC0 license](https://creativecommons.org/share-your-work/public-domain/cc0/); people are free to copy/paste your code into their projects with no impact on the licensing of those projects. This data is retained according to [Slack's data retention policies](https://slack.com/trust/privacy/privacy-policy#retention).

**When you participate in an Data Science Learning Community project,** we collect any data necessary for that project, such as a github repo url or demographic data for mentorship matching. We will only share any provided data as described in the terms of that particular project. Unless otherwise specified in the specific project, DSLC does not share data collected for such projects.

**DSLC does not sell or share your data with other companies or services.** However, as described above, other services used by DSLC may collect your data, specifically Slack Technologies, Google Analytics, and YouTube.

## How can I contact DSLC about privacy?

If you have any questions about privacy, please contact the Community administrators at rfordatasci@gmail.com.

## When did this privacy policy take effect?

This privacy policy took effect on December 12, 2020.
